spring.application.name=ariadna
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.docker.compose.file=compose.dev.yaml

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=15m
jwt.refresh-token-expiration=7d
